services:
  backend:
    image: rishimeena/insulin-backend:latest
    environment:
      - MONGO_URI=${MONGO_URI}
      - SECRET_KEY=${SECRET_KEY}
      - HOST=0.0.0.0
      - PORT=5001
      - DEV_FAKE_OTP=false
      - DEFAULT_COUNTRY_CODE=+91
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
      - EMAIL_ADDRESS=${EMAIL_ADDRESS}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    ports:
      - "5001:5001"

  frontend:
    image: rishimeena/insulin-frontend:latest
    depends_on:
      - backend
    ports:
      - "5173:80"
